### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by lucafaggianelli** [posva/vue-plugin-template#3]
Hi,

I got some issues when i try to `npm install` the vue plugin into the vue app, it fails in the postinstall script:

```
> yon run build:dll


> vue-adminlte@0.0.1 build:dll /home/luca/dev/projects-atlas/node_modules/vue-adminlte
> ls /home/luca/dev/projects-atlas/node_modules/vue-adminlte ; webpack --progress --config build/webpack.config.dll.js

dist  LICENSE  package.json  README.md	src
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/luca/dev/projects-atlas/node_modules/vue-adminlte/build/webpack.config.dll.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/luca/dev/projects-atlas/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/luca/dev/projects-atlas/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```

It seems that build/ folder is not copied in node_modules, so I added it in plugin package.json:
```
  "files": [
    "build",
    "dist",
    "src"
  ],
```
The above solves the missing build/ directory, though I have another issue for missing webpack plugins, notice that I don't have these plugins in the vue app from where i'm running `npm install my-vue-plugin`
```
ERROR in dll vuePluginTemplateDeps
Module not found: Error: Cannot resolve module 'style-loader' in /home/luca/dev/projects-atlas/node_modules/vue-adminlte
 @ dll vuePluginTemplateDeps

ERROR in dll vuePluginTemplateDeps
Module not found: Error: Cannot resolve module 'style-loader/addStyles.js' in /home/luca/dev/projects-atlas/node_modules/vue-adminlte
 @ dll vuePluginTemplateDeps

ERROR in dll vuePluginTemplateDeps
Module not found: Error: Cannot resolve module 'sockjs-client' in /home/luca/dev/projects-atlas/node_modules/vue-adminlte
 @ dll vuePluginTemplateDeps

ERROR in dll vuePluginTemplateDeps
Module not found: Error: Cannot resolve module 'vue-style-loader/lib/addStylesClient.js' in /home/luca/dev/projects-atlas/node_modules/vue-adminlte
 @ dll vuePluginTemplateDeps
```

any hint?

Thanks
Luca

**Comment by posva** [comment]
Oh, I thought I fixed that, remove this line from your package.json and republish: https://github.com/posva/vue-plugin-template/blob/master/template/package.json#L27

**Comment by lucafaggianelli** [comment]
yeah, it works! thanks
